apiVersion: v1
kind: Pod
metadata:
  labels:
    app: todo-app
  name: todo-app-pod
spec:
  containers:
    - name: postgres
      image: docker.io/postgres:17
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "todo-in-go"
    - name: todo-app
      image: todoapp:latest
      ports:
        - containerPort: 3000
          hostPort: 3000
